server:
  port: 8089 #cambié 8081 a 8089, ver docker-compose
spring:
  application:
    name: fraud
  data:
    mongodb:
      auto-index-creation: 'true'
      authentication-database: admin
      username: root
      database: fraud
      password: root
      port: '27017'
      host: localhost
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/