server:
  port: 8082
spring:
  application:
    name: fraud
  data:
    mongodb:
      auto-index-creation: 'true'
      authentication-database: admin
      username: root
      database: fraud
      password: root
      port: '27017'
      host: localhost